module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "test",
        "chore",
        "ci",
        "perf",
        "revert",
        "security",
        "content",
      ],
    ],
    "subject-case": [2, "never", ["start-case", "pascal-case", "upper-case"]],
    "header-max-length": [2, "always", 100],
    "scope-enum": [
      1,
      "always",
      [
        "layout",
        "nav",
        "home",
        "about",
        "projects",
        "articles",
        "contact",
        "github",
        "settings",
        "seo",
        "perf",
        "a11y",
        "deps",
        "ci",
        "docs",
        "security",
        "theme",
        "data",
      ],
    ],
  },
};
